#!/usr/bin/env bash
### setzer-poke -- poke a medianizer
### Usage: setzer poke <target>
###
### Update a <target> medianizer
set -e
[[ $1 ]] || setzer --bad-usage "$0"
DSVALUE=$(seth --to-address "$1")
echo $(seth send "$DSVALUE" "poke()")
