#!/usr/bin/env bash
### setzer-spread -- variance of 2 values in %
### Usage: setzer spread <value1> <value2>
###
### Returns % variance between <value1> and <value2>
set -e
[[ $# = 2 ]] || setzer --bad-usage "$0"

old=$1
new=$2

testforzero=$(bc <<< "${old} == 0")

if [[ ${testforzero} -eq 0 ]]; then
    swing=$(bc <<< "scale=10;(${new} - ${old}) / ${old} * 100")
    echo $swing
    exit
fi

echo 9999
