#!/usr/bin/env bash
### setzer-price-ls -- list all prices
### Usage: setzer price ls
set -e
coinbase=$(setzer price coinbase)
coinmarketcap=$(setzer price coinmarketcap)
cryptocompare=$(setzer price cryptocompare)
etherscan=$(setzer price etherscan)
gdax=$(setzer price gdax)
kraken=$(setzer price kraken)
poloniex=$(setzer price poloniex)
echo "Coinbase:       $coinbase"
echo "CoinMarketCap:  $coinmarketcap"
echo "CryptoCompare:  $cryptocompare"
echo "Etherscan:      $etherscan"
echo "GDAX:           $gdax"
echo "Kraken:         $kraken"
echo "Poloniex:       $poloniex"