#!/usr/bin/env bash
### setzer-volume -- get ether volume in USD from bitfinex
### Usage: setzer volume bitfinex
set -e

json=$(curl -sS "https://api.bitfinex.com/v1/pubticker/ethusd")
price=$(jshon <<<"$json" -Q -e volume -u)
echo $price
