#!/usr/bin/env bash
set -e
json=$(curl -sS "http://api.oasisdex.com/v1/markets/mkr/eth")
price=$(jshon <<<"$json" -e data -e price -u)
eth=$(setzer read 0x729D19f657BD0614b4985Cf1D82531c67569197B)
bc <<<"$price * $eth"
