#!/usr/bin/env bash
set -e
export LC_NUMERIC=C

sources="gdax gemini kraken bitstamp bitfinex"

price () {
  price+=($(timeout 5 setzer price "$1" 2> /dev/null || true))
}

for x in $sources; do
  price "$x"
done

[[ ${#price[@]} -lt 3 ]] && exit 1

tr " " "\n" <<< $(echo "${price[@]}") | datamash median 1
