#!/usr/bin/env bash
### setzer-read -- read dsvalue
### Usage: setzer read [<options>] <receiver> <sig> [<args>]
###    or: setzer read [<options>] <receiver> <data>
###
### Perform a local call to <receiver> without publishing a transaction.
###
### With <sig> of the form `<name>(<types>)', infer <data> from <sig>/<args>.
### With `name(<in-types>)(<out-types>)', also decode the return values.
###
### With `-B <block>', use the state of the blockchain as of <block>.
### With `-F <sender>', simulate calling <receiver> from <sender>
### With `-V <value>', simulate transferring <value> to <receiver>.
###
### See also seth-send(1), seth-estimate(1), seth-storage(1), seth-code(1).
set -e
[[ $1 ]] || setzer --bad-usage "$0"
DSVALUE=$(seth --to-address "$1")

now=$(seth call "$DSVALUE" "read()(bytes32)")
seth --to-fix 18 $(seth --to-dec "$now")