#!/usr/bin/env bash
### setzer-volume -- get ether volume in USD from poloniex
### Usage: setzer volume poloniex
set -e

json=$(curl -sS "https://poloniex.com/public?command=returnTicker")
volume=$(jshon <<<"$json" -Q -e USDT_ETH -Q -e quoteVolume -u)
echo $volume