#!/usr/bin/env bash
set -e
name=setzer
for file in ${0%/*}/$name-price-*; do
  if [[ -L $file ]]; then
    continue
  else
    if [[ "${file##*-}" != "ls" ]]; then
      printf "%14s : %s\\n" "${file##*-}" "$($file)"
    fi
  fi
done