#!/usr/bin/env bash
set -e
#set -x

if ! [[ $SETZER_BOT_INIT ]]; then
  export SETZER_BOT_INIT=1
  conf="/home/nanexcool/makerdao/setzer/default.conf"
  [[ -e $conf ]] && . $conf
  #export var2=$var2
fi
[[ $var2 ]] && echo $var2
echo $var2

sleep 5;
exec "$0" "$@"
exit

wrap() {
  res=$(${@} 2> /dev/null)
}

wrap seth chain
if [[ $res ]]; then
  echo Chain is $res
else
  echo 'error'
  sleep 5
  exec "$0" "$@"
fi
exit

res=$(setzer price gdaxa)
exit_status=$?
if [ $exit_status != 0 ];
  then
    echo Will exit with status $exit_status
    exit $exit_status
fi
echo Finished