#!/usr/bin/env bash
### setzer-volume -- get ether volume in USD from bittrex
### Usage: setzer volume bittrex
set -e

json=$(curl -sS "https://bittrex.com/api/v1.1/public/getmarketsummary?market=usdt-eth")
volume=$(jshon <<<"$json" -Q -e result -Q -e 0 -Q -e Volume -u)
echo $volume
