#!/usr/bin/env bash
set -e
json=$(curl -sS "https://www.binance.com/api/v3/ticker/price?symbol=BATBTC")
price=$(jshon <<<"$json" -e price -u)
#todo replace with 'setzer price btcusd'
json=$(curl -sS "https://api.pro.coinbase.com/products/BTC-USD/ticker")
btc=$(jshon <<<"$json" -e price -u)
bc <<<"$price * $btc" | awk '{printf "%f", $0}'
