#!/usr/bin/env bash
set -e
json=$(curl -sS "https://api.bittrex.com/api/v1.1/public/getticker?market=BTC-BAT")
price=$(jshon <<<"$json" -e result -e Last -u)
price=$(printf "%.9f" $price)
json=$(curl -sS "https://api.pro.coinbase.com/products/BTC-USD/ticker")
btc=$(jshon <<<"$json" -e price -u)
bc <<<"$price * $btc" | awk '{printf "%f", $0}'
