#!/usr/bin/env bash
### setzer-volume-yobit -- get ether volume in USD from yobit
### Usage: setzer volume yobit
set -e

json=$(curl -sS "https://yobit.net/api/2/eth_usd/ticker")
volume=$(jshon <<<"$json" -e ticker -e vol_cur -u)
echo $volume
