#!/usr/bin/env bash
### setzer-price -- get ether price in USD from poloniex
### Usage: setzer price poloniex
set -e

json=$(curl -sS "https://poloniex.com/public?command=returnTicker")
price=$(jshon <<<"$json" -Q -e USDT_ETH -Q -e last -u)
echo $price
