#!/usr/bin/env bash
### setzer -- manipulate feeds
### Usage: setzer [<options>] <command> [<args>]
###    or: setzer <command> --help
###
### Manipulate feeds and update data

OPTS="setzer [<options>] <command> [<args>]
setzer <command> --help
--
  Options:
C,config=file        configuration file
W,wait=seconds       seconds to wait between checks (default: 60)
auto                 run automatically without user intervention

  Gas options:
gas-start=gas        starting gas price per tx in Gwei
gas-inc=gas          amount to increment gas price per tx in Gwei
gas-max=gas          maximum gas price to pay per tx in Gwei
"

set -e

if ! [[ $SETZER_INIT ]]; then
  export SETZER_INIT=1
  [[ -e ~/.setzerrc ]] && . ~/.setzerrc
  [[ $(pwd) != ~ && -e .setzerrc ]] && . .setzerrc
fi

if [[ $2 = --help ]]; then
  exec "${0##*/}" help "$1"
elif [[ $1 = -* ]] && which "${0##*/}-$1" &>/dev/null; then
  exec "${0##*/}-$1" "${@:2}"
fi

eval "$(git rev-parse --parseopt -- "$@" <<<"$OPTS" || echo exit $?)"

while [[ $1 ]]; do
  case $1 in
    --)              shift; break;;

    -C|--config)     shift; export SETZER_CONF=$1;;
    -W|--wait)       shift; export SETZER_LOOP_SECONDS=$1;;

       --auto)              export SETZER_AUTO=yes;;

       --gas-start)  shift; export SETZER_INITIAL_GAS_PRICE=$1;;
       --gas-inc)    shift; export SETZER_GAS_PRICE_INCREMENT=$1;;
       --gas-max)    shift; export SETZER_MAX_GAS_PRICE=$1;;

    *) printf "${0##*/}: internal error: %q\n" "$1"; exit 1
  esac; shift
done

"${0##*/}-${1-help}" "${@:2}"
