#!/usr/bin/env bash
set -e
export LC_NUMERIC=C

mapfile -t sources < <(setzer sources polyusd)

addprice () {
  price=$(timeout 5 setzer price polyusd-"$1" 2> /dev/null || true)
  if [[ $price ]]; then
    if [[ $price =~ ^[+-]?[0-9]+\.?[0-9]*$  ]]; then
      prices+=( "$price" )
    fi
  fi
}

for x in "${sources[@]}"; do
  addprice "$x"
done

[[ ${#prices[@]} -lt 2 ]] && exit 1

tr " " "\\n" <<< "${prices[@]}" | datamash median 1