#!/usr/bin/env bash
### setzer-price-ls -- list all prices
### Usage: setzer price ls
set -e
cryptocompare=$(setzer price cryptocompare)
coinmarketcap=$(setzer price coinmarketcap)
coinbase=$(setzer price coinbase)
etherscan=$(setzer price etherscan)
gdax=$(setzer price gdax)
echo "CryptoCompare:  $cryptocompare"
echo "CoinMarketCap:  $coinmarketcap"
echo "Coinbase:       $coinbase"
echo "Etherscan:      $etherscan"
echo "GDAX:           $gdax"