#!/usr/bin/env bash
### setzer-poke -- poke a medianizer
### Usage: setzer poke <target>
###
### Update a <target> medianizer
set -e
[[ $# -ge 1 ]] || setzer --bad-usage "$0"
(set -x; seth send "$1" "poke()" "${@:2}")
