#!/usr/bin/env bash
### setzer-read -- read a dsvalue, dscache or medianizer
### Usage: setzer read <target>
###
### Returns a formatted value of <target> or fails if invalid
set -e
[[ $1 ]] || setzer --bad-usage "$0"
TARGET=$(seth --to-address "$1")

now=$(seth call "$TARGET" "read()(bytes32)")
seth --to-fix 18 $(seth --to-dec "$now")
