#!/usr/bin/env bash
### setzer-expires -- get expiration in seconds (< 0 means expired)
### Usage: setzer expires <target>
###
### get expiration in seconds (< 0 means expired)
set -e
[[ $# = 1 ]] || setzer --bad-usage "$0"
zzz=$(seth call "$1" "zzz()(uint256)")
zzz=$(seth --to-dec "$zzz")
now=$(date +%s)
echo $(expr $zzz - $now)
