#!/usr/bin/env bash
### setzer-volume-ls -- list all volumes
### Usage: setzer volume ls
set -e
gdax=$(setzer volume gdax)
kraken=$(setzer volume kraken)
poloniex=$(setzer volume poloniex)
echo "GDAX:           $gdax"
echo "Kraken:         $kraken"
echo "Poloniex:       $poloniex"