#!/usr/bin/env bash
### setzer-volume -- show ETH/USD volume from <source>
### Usage: setzer volume ls (lists all sources)
###    or: setzer volume <source>
set -e

name=setzer

if [[ $1 ]]; then
  # shellcheck disable=SC2018
  # shellcheck disable=SC2019
  source=$(tr A-Z a-z <<<"$1")
  exec "$0-$source"
fi

setzer help volume

for file in ${0%/*}/$name-volume-*; do
  if [[ -L $file ]]; then
    continue
  else
    [[ "${file##*-}" != "ls" ]] && commands+=("$file")
  fi
done

list-commands() {
  for x in "$@"; do
    echo "   ${x##*-}"
  done
}

cat <<.

Sources:

$(list-commands "${commands[@]}")

.