#!/usr/bin/env bash
### setzer-compute -- get what the medianizer value would be if updated
### Usage: setzer compute <medianizer>
set -e
[[ $1 ]] || setzer --bad-usage "$0"
sig="compute()(bytes32,bool)"
echo $(seth call "$1" "$sig")