#!/usr/bin/env bash
### setzer-void -- invalidate a feed
### Usage: setzer void <target>
###
### voids <target>. Read will fail, peek will return false
set -e
[[ $# = 1 ]] || setzer --bad-usage "$0"
TARGET=$(seth --to-address "$1")
(set -x; seth send "$TARGET" "void()")
