#!/usr/bin/env bash
set -e
json=$(curl -sS "https://cex.io/api/tickers/USD")
l=$(jshon <<<"$json" -e data -l)
for (( i=0; i<$l; i++ ))
do
    if [ $(jshon <<<"$json" -e data -e $i -e pair -u) == 'ETH:USD' ]
    then
        echo $(jshon <<<"$json" -e data -e $i -e last -u)
        break
    fi
done
