#!/usr/bin/env bash
cat <<.
setzer 0.1.4
Copyright (C) 2017  Mariano Conti <nanexcool@gmail.com
License: GNU GPL version 3 or later <https://gnu.org/licenses/gpl>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
.