#!/usr/bin/env bash
set -e
json=$(curl -sS "https://www.okex.com/api/spot/v3/instruments/MKR-ETH/ticker")
mkr_eth=$(jshon <<<"$json" -e last -u)
eth_usd=$(setzer price eth)
bc -l <<<"$mkr_eth * $eth_usd" | awk '{printf "%.10f", $0}'
