#!/usr/bin/env bash
### setzer-price -- show ETH/USD price from <source>
### Usage: setzer price ls (show all)
###        setzer price <source>
set -e
[[ $1 ]] || setzer --bad-usage "$0"
set -- "${1,,}"
exec "$0-$1"
