#!/usr/bin/env bash
set -e
json=$(curl -H 'Cache-Control: no-cache' -sS "https://api.etherscan.io/api?module=stats&action=ethprice&apikey=$SETZER_ETHERSCAN_API")
price=$(jshon <<<"$json" -e result -e ethusd -u)
echo "$price"
