#!/usr/bin/env bash
### setzer-volume -- get ether volume in USD from gemini
### Usage: setzer volume gemini
set -e

json=$(curl -sS "https://api.gemini.com/v1/pubticker/ethusd")
volume=$(jshon <<<"$json" -Q -e volume -Q -e ETH -u)
echo $volume
