#!/usr/bin/env bash
### setzer-volume -- get ether volume in USD from bitbay
### Usage: setzer volume bitbay
set -e

json=$(curl -sS "https://bitbay.net/API/Public/ETHUSD/ticker.json")
volume=$(jshon <<<"$json" -e volume -u)
echo $volume
