#!/usr/bin/env bash
# https://stackoverflow.com/questions/12199631/convert-seconds-to-hours-minutes-seconds/32164707#32164707
set -e
function displaytime {
  local T=$1
  local D=$((T/60/60/24))
  local H=$((T/60/60%24))
  local M=$((T/60%60))
  local S=$((T%60))
  [[ $D > 0 ]] && printf '%dd ' $D
  [[ $H > 0 ]] && printf '%dh ' $H
  [[ $M > 0 ]] && printf '%dm ' $M
  #[[ $D > 0 || $H > 0 || $M > 0 ]] && printf 'and '
  printf '%ds\n' $S
}
displaytime "$1"
