#!/usr/bin/env bash
### setzer-prod -- update a ds-cache
### Usage: setzer prod <target> <value> <timestamp>
###
### Update <target> with <value> and <timestamp> expiration
set -e
[[ $# = 4 ]] || setzer --bad-usage "$0"
wut=$(seth --to-uint256 $(seth --to-wei $3 ETH))
zzz=$(seth --to-uint256 "$4")
(set -x; seth send "$1" "prod(address,bytes32,uint128)" "$2" "$wut" "$zzz")
