#!/usr/bin/env bash
### setzer-price -- get ether price in USD from bittrex
### Usage: setzer price bittrex
set -e

json=$(curl -sS "https://bittrex.com/api/v1.1/public/getmarketsummary?market=usdt-eth")
price=$(jshon <<<"$json" -e result -e 0 -e Last -u)
echo $price
