#!/usr/bin/env bash
### setzer-price-cryptocompare -- get ether price in USD from cryptocompare
### Usage: setzer price cryptocompare
set -e

json=$(curl -sS "https://min-api.cryptocompare.com/data/price?fsym=ETH&tsyms=USD")
price=$(jshon <<<"$json" -e USD -u)
echo $price
