#!/usr/bin/env bash
set -e
export LC_NUMERIC=C

sources="bitstamp gdax gemini kraken"

addprice () {
  price=$(timeout 5 setzer price "$1" 2> /dev/null || true)
  if [[ $price ]]; then
    prices+=( "$price" )
  fi
}

for x in $sources; do
  addprice "$x"
done

[[ ${#prices[@]} -lt 3 ]] && exit 1

tr " " "\\n" <<< "${prices[@]}" | datamash median 1
